"""empty message

Revision ID: 52e6bab21a26
Revises: 7595b7ae25eb
Create Date: 2021-05-30 01:14:04.194966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e6bab21a26'
down_revision = '7595b7ae25eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room', 'primary_color',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=7),
               existing_nullable=True)
    op.alter_column('room', 'secondary_color',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=7),
               existing_nullable=True)
    op.alter_column('room', 'admin_key',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room', 'admin_key',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('room', 'secondary_color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    op.alter_column('room', 'primary_color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    # ### end Alembic commands ###
