"""empty message

Revision ID: 64b7d17d6ccc
Revises: fbd99441e98c
Create Date: 2021-06-04 22:58:45.415859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b7d17d6ccc'
down_revision = 'fbd99441e98c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('profile_pic', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('room', 'profile_pic')
    # ### end Alembic commands ###
