"""empty message

Revision ID: 7595b7ae25eb
Revises: 1be713b64400
Create Date: 2021-05-29 23:51:29.232430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7595b7ae25eb'
down_revision = '1be713b64400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('room_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.add_column('room', sa.Column('admin_key', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'admin_key')
    op.drop_table('users')
    # ### end Alembic commands ###
