"""empty message

Revision ID: 83b1209343a9
Revises: 64b7d17d6ccc
Create Date: 2021-06-05 19:02:08.895631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b1209343a9'
down_revision = '64b7d17d6ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('room_pic', sa.String(), nullable=True))
    op.drop_column('room', 'profile_pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('profile_pic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('room', 'room_pic')
    # ### end Alembic commands ###
