"""empty message

Revision ID: fbd99441e98c
Revises: 7bfc04642a7c
Create Date: 2021-05-30 17:10:40.832296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd99441e98c'
down_revision = '7bfc04642a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_entry', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('room', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'time_created')
    op.drop_column('room', 'time_created')
    op.drop_column('feedback_entry', 'time_created')
    # ### end Alembic commands ###
